# Generated by Django 4.2 on 2023-06-23 04:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_customuser_is_manager'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='business',
            name='products',
        ),
    ]
