# Generated by Django 4.2.2 on 2023-06-20 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_alter_product_case_size_alter_product_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
