# Generated by Django 4.2 on 2023-06-23 05:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_alter_business_name_alter_category_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='vendor',
        ),
        migrations.RemoveField(
            model_name='product',
            name='vendor_product_number',
        ),
    ]
