# Generated by Django 4.2 on 2023-07-03 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_customuser_business_inventory_inventory_items'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='pack_type',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
