# Generated by Django 4.2.2 on 2023-06-20 05:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_inventory_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventory',
            name='product',
        ),
        migrations.RemoveField(
            model_name='monthlyinventory',
            name='product',
        ),
        migrations.AddField(
            model_name='monthlyinventory',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='monthlyinventory',
            name='products',
            field=models.ManyToManyField(to='inventory.product'),
        ),
        migrations.CreateModel(
            name='InventoryItem',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.IntegerField()),
                ('inventory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inventory.inventory')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_items', to='inventory.product')),
            ],
        ),
        migrations.AddField(
            model_name='inventory',
            name='inventory_items',
            field=models.ManyToManyField(related_name='inventories', to='inventory.inventoryitem'),
        ),
    ]
