# Generated by Django 4.2 on 2023-06-23 05:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_remove_product_vendor_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inventoryitem',
            old_name='inventory_name',
            new_name='inventory_id',
        ),
    ]
