# Generated by Django 4.2 on 2023-06-23 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_rename_inventory_name_inventoryitem_inventory_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventoryitem',
            name='inventory_id',
            field=models.IntegerField(max_length=10000, null=True),
        ),
    ]
