# Generated by Django 4.2.2 on 2023-06-20 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_remove_inventory_quantity_remove_inventory_total_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventoryitem',
            name='inventory',
        ),
    ]
