# Generated by Django 4.2 on 2023-07-05 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_remove_product_product_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='case_size',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='count_by',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.FloatField(max_length=100, null=True),
        ),
    ]
