# Generated by Django 4.2 on 2023-06-23 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_alter_inventoryitem_inventory_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventoryitem',
            name='inventory_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='quantity',
            field=models.FloatField(default=0),
        ),
    ]
