# Generated by Django 4.2 on 2023-06-20 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_remove_inventoryitem_inventory'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inventoryitem',
            old_name='id',
            new_name='inventory_item_id',
        ),
        migrations.AlterField(
            model_name='inventory',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='inventory_items',
            field=models.ManyToManyField(null=True, related_name='inventories', to='inventory.inventoryitem'),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
