# Generated by Django 4.2 on 2023-06-20 21:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_rename_id_inventoryitem_inventory_item_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='inventory',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='inventory.inventory'),
        ),
    ]
