# Generated by Django 4.2 on 2023-07-06 16:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_alter_product_case_size_alter_product_count_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryitem',
            name='sub_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inventoryitems', to='inventory.subcategory'),
        ),
    ]
