# Generated by Django 4.2 on 2023-06-21 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_location_inventory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='inventory',
        ),
        migrations.AddField(
            model_name='business',
            name='products',
            field=models.ManyToManyField(related_name='businesses', to='inventory.product'),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='price',
            field=models.FloatField(default=0.0),
        ),
    ]
