# Generated by Django 4.2 on 2023-07-13 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0010_inventory_user_alter_customuser_business'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='item_list',
            field=models.ManyToManyField(related_name='item_lists', to='inventory.inventoryitem'),
        ),
    ]
