# Generated by Django 4.2 on 2023-07-13 21:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0011_alter_inventory_item_list'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventory',
            name='inventory_items',
        ),
    ]
