# Generated by Django 4.2 on 2023-06-21 17:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0011_alter_inventoryitem_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventory',
            name='inventory_items',
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='inventory',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inventory_items', to='inventory.inventory'),
        ),
    ]
