# Generated by Django 4.2 on 2023-06-21 17:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0012_remove_inventory_inventory_items_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='inventory_item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inventories', to='inventory.inventoryitem'),
        ),
        migrations.DeleteModel(
            name='MonthlyInventory',
        ),
    ]
