# Generated by Django 4.2 on 2023-07-17 16:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0013_delete_productmixtemplate'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='customUser',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='businesses', to=settings.AUTH_USER_MODEL),
        ),
    ]
