# Generated by Django 4.2 on 2023-07-17 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0014_business_customuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='business',
            name='customUser',
        ),
    ]
