# Generated by Django 4.2 on 2023-07-17 16:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0015_remove_business_customuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='users',
            field=models.ManyToManyField(related_name='businesses_customuser', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='business',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customusers', to='inventory.business'),
        ),
    ]
