# Generated by Django 4.2 on 2023-06-21 19:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0015_alter_inventory_location_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductMixTemplate',
            fields=[
                ('product_mix_template_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productmixtemplates', to='inventory.business')),
                ('item_list', models.ManyToManyField(related_name='productmixtemplates', to='inventory.product')),
            ],
        ),
    ]
