# Generated by Django 4.2 on 2023-06-21 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0016_productmixtemplate'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='month',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='inventory',
            name='year',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
