# Generated by Django 4.2 on 2023-06-21 20:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0017_inventory_month_inventory_year'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productmixtemplate',
            name='business',
        ),
        migrations.AddField(
            model_name='productmixtemplate',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='productmixtemplates', to='inventory.location'),
        ),
    ]
